# GoReleaser v2 configuration
version: 2

project_name: super
builds:
  - main: ./cmd/super
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -X github.com/brimdata/super/cli.version={{ .Tag }}
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    hooks:
      post:
      - cmd: >
          sh -c '{{ if eq .Os "windows" }}CodeSignTool sign
          -username="{{ .Env.SSLDOTCOM_USERNAME }}"
          -password="{{ .Env.SSLDOTCOM_PASSWORD }}"
          -credential_id="{{ .Env.SSLDOTCOM_CREDENTIAL_ID }}"
          -totp_secret="{{ .Env.SSLDOTCOM_TOTP_SECRET }}"
          -input_file_path="{{ .Path }}"{{ else }}true{{ end }}'
notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - super
      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{ .Env.MACOS_SIGN_PASSWORD }}"
      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"
        wait: true
archives:
  - name_template: "{{ .ProjectName }}-{{ .Tag }}.{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [ "zip" ]
    files:
      - LICENSE.txt
      - acknowledgments.txt
release:
  header: |
    View [change log](CHANGELOG.md#{{ replace .Tag "." "" }}).
checksum:
  name_template: 'super-checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-{{ .ShortCommit }}"
changelog:
  disable: true
